### ISSUE TITLE
[FEATURE] Add Filter/Search to Load Marker List

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#132]
# Description

When maintaining the markers for a session, there is an option to load markers from the global marker pool from previous sessions into the current session. That list of markers is currently not filterable, but just a list to scroll through.

The list should be filterable by:
* Marker Name
* Marker Description
* Marker Abbreviation

# Tasks

- [x] Implement Filter for Marker Name
- [x] Implement Filter for Marker Description
- [x] Implement Filter for Marker Abbreviation
