### ISSUE TITLE
[FEATURE] Delete Session

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#19]
# Description

The deletion of a session should be a soft delete. Deleted sessions are not shown to the user in the sessions overview list any more.

# Tasks

- [x] Implement GraphQL Endpoint for Session delete
- [x] Implement Automated Tests for GraphQL Endpoint
- [x] Implement UI delete operation for session
- [x] Implement E2E tests for session delete

**Comment by TaSpatzHfM** [comment]
Concerning further use of the data of the sessions (f.e. for possible meta-studies), I would prefer the soft delete.

**Comment by TS-Daniel16** [comment]
Pending release. Feature completed.

Includes:
- Soft delete of sessions from the session overview table
- Confirmation dialog that session should be deleted

**Comment by TS-Daniel16** [comment]
Release available now (v.0.5), closing issue.
