### ISSUE TITLE
[FEATURE] Setup Documentation Project

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#2]
# Description

Create Github Pages for KoALa project where documentation how to run, deploy, develop, etc is explained. Initial content can be added, but will be extended with every feature.

# Tasks

- [x] Create Github Page
- [x] Decide on Documentation Structure and Framework
- [x] Add search to docs
- [x] Setup GitHub Actions to deploy documentation

**Comment by TS-Daniel16** [comment]
@TS-Tino16 structure and search is done right?
