### ISSUE TITLE
[FEATURE] Update Basic Session Data of Existing Session

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#22]
# Description

All basic data from the session is updateable. The only mandatory entry is the session name. Basic data is data on the first tab in the session maintain view.

# Tasks

- [x] Implement Update Endpoint for Session Data
- [x] Implement Update of Session Data in UI
- [x] Automated UI tests
- [x] Automated API tests

**Comment by TS-Daniel16** [comment]
Review and release pending
