### ISSUE TITLE
[FEATURE] Add Control Data to Session Creation

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#28]
# Description

The following data can be maintained for a session:

- [x] Name: short description to identify session; no uniqueness check (done in walking skeleton)
- [x] Description: longer description of session with possible multiple lines and line breaks; no rich editor functionality (bold, italic, font, font size, etc.)
- [x] Session Status: [In Preparation, Open, Closed, Archived]
- [x] Online: Replaced by Session Status
- [x] Editable ("Bearbeitung"): used as default for session handling (edibility for participants)
- [x] Start and End dates: end dates needs to be later to start date; only editable in case "online" flag is not set
- [x] Player: is used as a default for session handling (decides if participants can play the audio on their own)
- [x] Sample Solution: used as default for session handling (showing the sample solution or not)
- [x] Analysis: used as default for session handling (show analysis of annotations or hide it)

# Tasks

- [x] Sychronous/aynchronous field can be removed (the function is covered by enabling/showing the player)
- [x] Session Status (In Preparation, Open, Closed and Archived as options)

# Open Questions

- [x] Is composer field needed
- [x] Editable ("Bearbeitung") defines what?
- [x] Start and End dates: what is defined by these dates? is the interpretation dependent on other data?
- [x] Sample Solution: why is this necessary to be defined on session level already? Isn't it enough to either have one or to not have a sample solution available? What is controlled by this checkbox?
- [x] Analysis: same as sample solution, what is the purpose of this checkbox in the user flow?
- [x] Player: defines if player is available to participants (does it also define if everyone can play the audio themselves or if it is also just shown as visualization and the "editable" option defines that it is playable by participants?
- [x] Definition of status and status flow: how does the status interact with "online"
- [x] Status: what does "Session Closed" mean? Still shown in session overview? Or just not editable any more for anyone?
- [x] Online: how does the interaction between the dates and the flag work? As soon as the flag is set the dates are irrelevant and should be not editable/avvailable?

**Comment by mxordn** [comment]
I comment here after our discussion yesterday regarding session attributes.

- [ ] sychronous/aynchronous field can be removed (the function is covered by enabling/showing the player)
- [ ] in my opinion the availability timespan in the „Freigaben“ section is not necessary. It doubles the timespan in the „Verfügbarkeit“ section in my eyes. Or am I overlooking a use case?
- [ ] A checkbox that says, if the session is open or closed (editable/not editable) would be good, an optional timespan that defines availability (i.e. visibility/accessibility for the subscribed users) of the session is in some cases interesting. Similar functions in a learning platforms like ILIAS or moodle are popular.
- [ ] Audio upload may not necsessarily require a metadata field like composer. This can be part of the session description, if information to the audio track is required.
- [  the Marker section is to be added. I Opened the discussion here: …

These are my observations so far. Please feel free to comment on, add or remove the points above.

**Comment by TS-Daniel16** [comment]
@KoALa-MHF/mh-team I have created a list of data points which can be entered for a session in the issue description above. Also for some on these data points we have questions what they are used for, which I have added in section "Open Questions". Please go through them and provide us a short description (like we did for the other fields) which helps the understanding here. Would be also good if you not just start from a delta list, but more a complete list of data entries which you need for a session

**Comment by mxordn** [comment]
- Composer Field is not needed. I think such information can go to the session description. I don't have an idea of where this field appears again later during the usage of the session
- with online I understand the session is available for the participants. If the session is not online participants should be directed to a screen that says e.g. that the session they try to join is not (yet) „live“. The terminology is used in ILIAS (elearning) platforms in a similar way. Owners can create an object (here a session), but don't publish this immediately to all class members. So publish might also be a good word for it.
- Editable means that participants are able to write annotations into the session. If the box is not checked markers do not have any effect. Background: in class you might want to have the option to direct attention of the participants.
- start and end dates have effect on the „online“ field. They work as clock timer (Zeitschaltuhr) for the online Attribute.
    - This means that the field can be removed in the audio track section. As mentioned in the above comment.
- the checkbox sample solution controls the visibility of the solution for the participants. The Owner should be able to hide oder show his/her solution. A better label would be „Musterlösung anzeigen“
- The usage of Analyse checkbox is unclear for me.
- Player: The checkbox controls if participants can play the audio file on their own. If not checked the session audio is controlled by the owner (all hear at the same time). The checkbox is doing basically what synchronous and asynchronous stood for before. In contrary to the editable checkbox the player checkbox doesn't have any effect on the markers.

**Comment by TS-Daniel16** [comment]
ok, so most of them are only for handling during an active session (display option, etc.). Does it then make sense to define them already when creating a session or wouldn't it make more sense to have these options inside of the session screen (e.g. to show a sample solution is in the end just a display option, not a setting of the session which has to be stored anywhere)

* Online: since we have anyways a status (Open, Closed) wouldn't that be just another status in the status sequence: Open => Active => Closed? That would also reduce the data maintenance screen or should it be display only because of the start end date interpretation (see next point)
* Start and End date: if they control the online "status", this is not data which you want to store, but you derive for display purposes from the dates
* Player: does that mean that the player is not shown at all as soon as I can not play it as a participant? Until now our understanding was that a visualization and synchronization with the current play position of the owner is wanted, but not always wanted; or does it mean that the player is always visible (just not playable) depending on the checkbox and only if there is no audio (live situation) the player is not visible?
* Editable: that also sounds more like an active session control than having it as a master data in the session maintenance

**Comment by mxordn** [comment]
> ok, so most of them are only for handling during an active session (display option, etc.). Does it then make sense to define them already when creating a session or wouldn't it make more sense to have these options inside of the session screen (e.g. to show a sample solution is in the end just a display option, not a setting of the session which has to be stored anywhere)

Exactly, the checkboxes Musterlösung, Bearbeitung (editable) and Player should be available in the session screen. But it makes some sense to define them already when the session is created in order to be able to prepare the starting status of a session.

> Online: since we have anyways a status (Open, Closed) wouldn't that be just another status in the status sequence: Open => Active => Closed? That would also reduce the data maintenance screen or should it be display only because of the start end date interpretation (see next point)

I would stay with the binary status open and closed which means (publicly available for participants or not). This is a checkbox that is not neccessary during the session and within the session screen. But it could be a direct option on the session list.

> Start and End date: if they control the online "status", this is not data which you want to store, but you derive for display purposes from the dates

I don't know if I understand correctly. I would put like this: The Start and End date controls the open closed checkbox value. E.g. you could say the session is available from Start day and you can do your annotations until End date. So the status of the online open|closed checkbox is derived from the dates.

If this is complicated to implement as it requires some extra logic I would drop that feature.

> Player: does that mean that the player is not shown at all as soon as I can not play it as a participant? Until now our understanding was that a visualization and synchronization with the current play position of the owner is wanted, but not always wanted; or does it mean that the player is always visible (just not playable) depending on the checkbox and only if there is no audio (live situation) the player is not visible?

The last one is it. The Player checkbox affects primarily the controls of the audio player. If checked every participants can use the player autonomously. If not checked controls (play, stop, pause etc…) are only in the hands of the owner and the play position should be indicated along the timeline as you wrote.

**Comment by TS-Daniel16** [comment]
> I don't know if I understand correctly. I would put like this: The Start and End date controls the open closed checkbox value. E.g. you could say the session is available from Start day and you can do your annotations until End date. So the status of the online open|closed checkbox is derived from the dates.
> 
> If this is complicated to implement as it requires some extra logic I would drop that feature.

@mxordn since this is the "master data" maintenance view for a session, typically the checkbox would not be set according to the inference from start and end date. Also my point was going into a direction that the information contained in the "online" checkbox is just a display option, not something that needs to be explicitly set by the user and hence need to be stored on the DB

**Comment by TS-Daniel16** [comment]
Audio title and composer fields have been removed as discussed

**Comment by TS-Daniel16** [comment]
Audio file handing in #46

**Comment by TS-Daniel16** [comment]
@KoALa-MHF/mh-team I have added some more questions in the "Open Questions" section. The handling of the "online" flag in combination with the dates is not yet completely clear to us. The status and how that interacts with the "online" flag should also be clarified. Could you maybe give a short explanation/answer about the open questions in the issue description?

**Comment by mxordn** [comment]
- Definition of status and status flow: how does the status interact with "online"

Online means something like "ready to use". The dates are controlling accessibility for the users. In my opinion it makes no sense to store dates without having checked online.

- Status: what does "Session Closed" mean? Still shown in session overview? Or just not editable any more for anyone?

Yes if checked the session is not editable.

- Online: how does the interaction between the dates and the flag work? As soon as the flag is set the dates are irrelevant and should be not editable/avvailable?

See above.

**Comment by s-platte** [comment]
**Status "Session Closed":**
"Session Closed" means that it is not editable for users, but the owner can still add annotations (sample solutions). 

**Status "Session online" and dates:**
I think the dates should be not editable when "online" is checked, because in this case the session is online without any limitations. As soon as dates are added, the online checkbox turns into checked and not editable (light grey), because the status is then defined by the given timeframe.

**Comment by TS-Daniel16** [comment]
Open topic: session status

**Comment by TS-Daniel16** [comment]
Possible status of a session would be:

* In Preparation
* Open/Online
* Closed
* Archived

Deletion would not be a status, would be handled separately.

@KoALa-MHF/mh-team is this list from our alignments complete or do you see other possible status?

**Comment by TS-Daniel16** [comment]
Additional accordion section for archived section (underneath other sessions section)

**Comment by TS-Daniel16** [comment]
Status flow has no restriction, that means you can select any status as a follow up status to any status (e.g. archived to in preparation)
