### ISSUE TITLE
[FEATURE] Create Session with Session Name

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#4]
# Description

As a first step, a very simple session should be possible to be created, which means giving a name to the session.

With this feature the UI as well as server and database part should be created. This should serve as a walking skeleton for other features.

# Tasks

- [x] Create DB entity for session
- [x] Create server endpoint to create session with name
- [x] Check that name is not empty
- [x] Create frontend to enter session name and trigger create
- [x] Automatic Test is created checking the following:
  - [x] Session is created with given name
  - [x] Session without a name returns error

**Comment by TS-Daniel16** [comment]
@KoALa-MHF/mh-team we defined the session name as unique since in a list of sessions one might want to differentiate between sessions just by scanning the session name. What are your thoughts regarding this?

**Comment by mxordn** [comment]
In general, yes. It's a good decision. In a list of sessions that totally makes sense.

(1) Is the space free again after having deleted the session?

(2) Is it unique for one owner or regarding all global available sessions?
If it is globally unique, I would be careful, because there might be some works used very often. That might cause a very limited name space. To avoid this a recommendation might be given to the owners e.g. to add a date?

**Comment by TS-Daniel16** [comment]
@mxordn @KoALa-MHF/mh-team 

(1) This depends on if the session delete is a soft or hard delete (soft = stays on database, but will not be displayed any more; hard = data is completely removed and cannot be retrieved again). I have created issue #19 to further discuss the session delete mechanism. If it is a soft delete, the name would still be blocked. If it is a hard delete, the name would be free again.

(2) The name would be unique globally.

I guess just from a user's perspective, you would create a session for a certain purpose which you would reflect in the session name (and not just putting the music title there for example), to allow yourself to use the same music piece in multiple sessions and still be able to distinguish between them. Maybe you can confirm that this assumption is correct? Then the only conflicts you might have are session names from other users, which fulfill the same criteria as your session. In that case, would it be acceptable to tell the user to add something to make it unique (which is not far from the chosen text in most cases I guess).

**Comment by mxordn** [comment]
> I guess just from a user's perspective, you would create a session for a certain purpose which you would reflect in the session name (and not just putting the music title there for example), to allow yourself to use the same music piece in multiple sessions and still be able to distinguish between them. Maybe you can confirm that this assumption is correct? 

Yes that seems right. The longer I think about it, the more I think that unique session names are a good idea. I think it pushes users to be clear with their titles.

Maybe we can have suggestions for good names, e.g. with a placeholder text in the textfield. I'm ok with it. what do the others (@KoALa-MHF/mh-team ) say?

**Comment by TaSpatzHfM** [comment]
A unique session name is a good idea - but only in combination with placeholders/suggestions for good names (at least from my point of view). Without these suggestions, I would be afraid that the "basic" names (f.e. composer + work) would be blocked very soon.

**Comment by s-platte** [comment]
What if we allow unique sessions names which are freely chosen by the users and then automatically create an alias (i.e. a session id)? In this way we could avoid conflicts with identical sessions-names and still give the user the freedom to choose whatever name they want.

**Comment by TS-Daniel16** [comment]
@s-platte in the end the session entity is designed with such a session id as database key anyway. The uniqueness check of the name would be on top and is just for user experience improvement. If identical session names are wanted and ok and the differentiation is based on the owner (how likely is it that an owner creates two sessions with the same name?) or the description, then that would be easier than generate additions to the session name which might be confusing to the user.

Also that approach (allowing same session names) is more user friendly with regards to the soft delete.

@TaSpatzHfM would it be a bad thing if a name would be "blocked" early and the user is forced to specify additions to the name to make it unique? It's not like it is important to reserve these kind of names (like for domains to popup at the top in the google search) for any benefits correct?

**Comment by mxordn** [comment]
> The uniqueness check of the name would be on top and is just for user experience improvement. If identical session names are wanted and ok and the differentiation is based on the owner (how likely is it that an owner creates two sessions with the same name?) or the description, then that would be easier than generate additions to the session name which might be confusing to the user.

I think it could easily be the case, that a user is typing the same title twice. But I don't think that this is problematic as long as you see e.g. the date when it was generated. If the soft deletion goes better with no unique names (a point that I see) then I vote for allowing equal session names.

> It's not like it is important to reserve these kind of names (like for domains to popup at the top in the google search) for any benefits correct?

No that's not planned and maybe also not wanted :).

**Comment by TS-Daniel16** [comment]
@KoALa-MHF/mh-team Proposal for now would be: we go ahead with a non-unique session name in the beginning, designing it in a way that we could add this check later and after you can experience on the website we'll discuss what feels more natural to a user. Is that ok for you?

**Comment by mxordn** [comment]
I have another topic regarding the session data. Maybe the synchronous/asynchronous division is not necessary, because it is more or less the same as the player yes/no option.

Following thoughts:
- Owner decides to disable the player -> no audio is delivered to the clients, player simply shows a timeline.
- Owner decides to enable player -> audio is delivered to users that are logged in. All others stay with the above player

I think this gives the owner enough power to switch between synchronous and asynchronous session usage also within a lesson.

**Comment by TS-Daniel16** [comment]
I would move that discussion to #28 since this issue is just about creating a session with a session name. I have copied the comment to the issue.

**Comment by TS-Daniel16** [comment]
@KoALa-MHF/mh-team when switching to a tabs maintenance mode, the challenge was how to handle mandatory fields (when creating the session on server side) and still be able to start on any tab you like (like adding markers to the session). To not create an empty session container in the background and then fill it in the session maintenance page, we have added a small dialog when the "Create Session" button is pressed in the session overview page where the session name has to be entered before the session maintenance page (with the tabs) is entered (making it prettier still pending ;)):

<img width="1440" alt="Bildschirmfoto 2022-12-18 um 17 25 59" src="https://user-images.githubusercontent.com/99263623/208308806-77a454e8-7f7d-4a9a-921b-7ed96e5c48bc.png">

Since this is a typical pattern in the web application world, the users should be able to recognize this behavior and should not be surprised by it.

With this change we would then also close this issue, since you are able to create an initial session with a session name. Additional session properties are handled in other issues.

**Comment by TS-Daniel16** [comment]
Summary of behavior:

* Creation of session is done via dialog with one input field for the session name
* Session name is not unique (there could be two sessions named 'ABC')
* The creation of a session is only possible if a session name with at least 1 character is provided in the dialog
* After the dialog entry is completed, the user is forwarded to the session maintenance page for further details to be maintained (of which none are mandatory)

**Comment by TS-Daniel16** [comment]
@KoALa-MHF/mh-team This issue can be closed from our side. If you agree, just comment here and we'll close it.
