### ISSUE TITLE
[FEATURE] Audio File Upload

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#46]
# Description

During a session create an audio file should be possible to upload. The audio file is stored on the file system of the host machine and is connected to the session where it is created.

When the session is deleted, the audio file is deleted as well (hard delete).

When the session is updated with a new audio file upload, the formerly attached audio file is deleted (hard delete).

File size limit: 100MB
Files supported: mp3, wav

# Tasks

- [x] Implement API Endpoint to Upload Files (and store the file in the file system)
- [x] Implement UI to upload audio file (offering standard file system browser to select the file to upload)
- [x] Implement audio file to media entity connection in API
- [x] Implement update mechanism of attached audio file (deleting old audio file, adding new audio file)
- [x] Add automated UI tests
- [x] Add automated API tests

**Comment by mxordn** [comment]
> When the session is deleted, the audio file is deleted as well (hard delete?).

Yes, hard delete is a good idea. It keeps the filesystem clean. 

> When the session is updated with a new audio file upload, the formerly attached audio file is deleted (hard delete).

Yes, same as above.

**Comment by mxordn** [comment]
To address the open question above.

> File size restrictions?

I think a normal mp3 used in our settings is between 1 MB and 10 MB. To allow even an hour of music with 192 kbps 80 MB might be sufficient. And a good limit is maybe 100 MB.

> File type restrictions?

My suggestion is mp3 and wav if that is supported by the the frameworks and browsers.

**Comment by TS-Daniel16** [comment]
Changed the limit in the issue description to 100MB and supported formats to mp3 and wav (@mxordn wav seems to be supported by wavesurfer.js)

**Comment by TS-Daniel16** [comment]
@TS-Tino16 can you comment on the update process

**Comment by TS-Daniel16** [comment]
@TS-Tino16 is the replacement of the audio file in a subsequent upload already in the release?

**Comment by TS-Tino16** [comment]
> @TS-Tino16 is the replacement of the audio file in a subsequent upload already in the release?

not yet

**Comment by TS-Daniel16** [comment]
Update added with #314

**Comment by TS-Daniel16** [comment]
Included in version 0.9.0
