### ISSUE TITLE
[FEATURE] Display List of Existing Sessions With Their Names

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#5]
# Description

With this feature, the created sessions from #4 should be shown in a list/table displaying the session name. Styling and navigation patterns are not part of this yet, we'll use standard styles from angular material.

# Tasks

- [x] Create Endpoint on server side to expose read access to sessions (name as only data at this point)
- [x] Display all sessions in list/table in frontend
- [x] Implement Automated UI Tests
- [x] Implement Automated API Tests

**Comment by TS-Daniel16** [comment]
@KoALa-MHF/mh-team this topic is done from our side. Please comment here, if it is also ok from your side, then we'll close it.

**Comment by s-platte** [comment]
Yes, feel free to close this topic.
