### ISSUE TITLE
[FEATURE] Login Page for Authenticated and Non-Authenticated Users

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#59]
# Description

* Login via username and password
* Login via session code (individual and general)
* Session overview is only reachable for authenticated users (username/password)
* Session maintenance is only available to authenticated users (username/password)

# Tasks

- [ ] Implement UI Login Screen with Code and Username/Password Combination Entry Possibilities
- [ ] Implement Guards to Block Access to Non-Authenticated Users (session overview, session maintenance)

# Open Questions

- [ ] Is authentication done via username and password or other combinations?

**Comment by TS-Daniel16** [comment]
#98 adds a first version of the login page with user session code authentication and guarding the following pages

**Comment by TS-Daniel16** [comment]
Username/password authentication will be done through Shibboleth / SAML, so there will not be an KoALa specific implementation for username and password entry.

Session code and user session code login is working in a first version.
