### ISSUE TITLE
[FEATURE] Add Impressum to KoALa Website

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#60]
# Description

Impressum is a mandatory part of a non-private website. This needs to be added to the KoALa website and the GitHub pages documentation site.

# Tasks

- [x] Write Impressum for KoALa website and documentation website
- [x] Include Impressum in KoALa website
- [x] Include Impressum in KoALa documentation website

**Comment by TS-Daniel16** [comment]
@KoALa-MHF/mh-team the first part (writing the impressum / content of impressum) would be a task for you. Once you have created the text, we can add it to the website and documentation.

**Comment by s-platte** [comment]
Hopefully soon. We are currently looking for a professional to review our draft as the original expert is no longer available. The text is already written - we just need a legal check from an expert in data protection.

**Comment by TS-Daniel16** [comment]
@s-platte we saw that you have an impressum page on the announcement page now. Is that the impressum we should also take over to the koala app site?

**Comment by TS-Daniel16** [comment]
@KoALa-MHF/mh-team could you add the impress content to this issue that we can add it to the website?

**Comment by TS-Daniel16** [comment]
impress is added and deployed
