### ISSUE TITLE
[FEATURE] i18n for App and Documentation

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#62]
# Description

Introduce translatable texts for the KoALa app UI and the docusaurus documentation. The following things should be supported:

* Language is derived from browser language first if it is german, english or french
* A user can change the language between german, english and french
* Fallback language in case of e.g. a translation is missing is always german

# Tasks

- [x] Introduce UI i18n via ngx-translate with the language selection as described above
- [x] Adjust all existing texts to be translatable texts
- [ ] Adjust build process to include translations
- [x] Offer UI for language switch (with local personalization)
- [x] Enable docusaurus documentation for i18n

**Comment by TS-Daniel16** [comment]
@s-platte hope this covers what you also asked in your email. Idea is that a user can switch themselves in the UI independent of the browser setting, but the browser setting would be the default (that is one reason why we prefer nix-translate over angular i18n to avoid reloading the whole page with every language switch). I have defined german as the fallback in case the browser language is not found or a translation is missing, but it is an open point for you if the fallback is english or german

**Comment by TS-Daniel16** [comment]
@TS-Tino16 you can take over the docusaurus part, app part is done

**Comment by TS-Daniel16** [comment]
Docusaurus issue resolved. GraphQL generation tool works with i18n.

**Comment by TS-Daniel16** [comment]
@TS-Stefan any possibility to potentially enhance NGINX settings to use requested language in request to forward for docusaurus differently?
