### ISSUE TITLE
[FEATURE] Add Renovate Bot

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#9]
# Description

To keep dependencies up to date, an automatic mechanism shall be introduced to update the used dependent packages (e.g. renovate bot).

It should run once per week and creates pull requests which need to be manually merged.

# Tasks

- [x] Automatic update of dependencies added
- [x] Runs once per week, but needs to be executed before a release
- [ ] Configure renovate bot

**Comment by TS-Tino16** [comment]
Added Renovate App to the project 

Open: needs to be configured

**Comment by TS-Tino16** [comment]
- Check if Renovate Bot is still running
- Configuration not needed

**Comment by TS-Tino16** [comment]
> * Check if Renovate Bot is still running
> * Configuration not needed

Validated current configuration - works fine for us
